name: CD

on:
  push:
    branches:
      - main
      - beta

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    name: CD
    runs-on: ubuntu-latest

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: node - setup
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

        # pnpm stuff
      - name: pnpm - setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: pnpm - install
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x
      - name: pnpm - config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: pnpm - output bin stubs
        run: echo "#! /usr/bin/env node" > ./packages/presta/cli.js
      - name: pnpm - install
        run: pnpm install

      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.TRUEWORK_TEAM_NPM_TOKEN }}
        run: npx semantic-release
